# Generated by Django 3.2.5 on 2021-07-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amiibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amiiboSeries', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('gameSeries', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('tail', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
